# .streamlit/secrets.toml

[connections.postgresql]
dialect = "postgresql"
host = "db.fpfstbiqwrpdfcvgcyo.supabase.co"
port = 5432
database = "postgres"
username = "postgres"
password = "Ai_MCQ@Project2"