[connections.postgresql]
url = "postgresql://postgres:AiMCQProject2026@db.fpfstbiqpwrdpfcvgcyo.supabase.co:6543/postgres?sslmode=require"
dialect = "postgresql"
host = "db.fpfstbiqwrpdfcvgcyo.supabase.co"
port = 5432
database = "postgres"
username = "postgres"
password = "AiMCQProject2026"