[connections.postgresql]
url = "mysql://avnadmin:AVNS_gHTT0Fcpm7LSxGu_eb0@mysql-1d9c56de-ai-mcq-project.l.aivencloud.com:24594/defaultdb?ssl-mode=REQUIRED"
dialect = "postgresql"
host = "db.fpfstbiqwrpdfcvgcyo.supabase.co"
port = 6543
database = "postgres"
username = "postgres"
password = "AiMCQProject2026"